ViewModels/AddCustViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TCSBanking.Models;

namespace TCSBanking.ViewModels
{
    public class AddCustViewModel
    {
        [Required(ErrorMessage ="Please Enter 9 digit SSN")]
        public int Ssnid { get; set; }

        [Required(ErrorMessage ="Enter Customer Name")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Enter Customer address")]
        public string Address1 { get; set; }

        public string Address2 { get; set; }

        [Required(ErrorMessage ="Enter Customer Age")]
        public int Age { get; set; }

        public List<UserInfo> UserInfos { get; set; }
    }
}

ViewModels/DeleteCustViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TCSBanking.ViewModels
{
    public class DeleteCustViewModel : AddCustViewModel
    {
        public int Id { get; set; }
    }
}

Controllers/CustStatusBankController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TCSBanking.Extensions.Alerts;
using TCSBanking.Models;
using TCSBanking.Repositorys;
using TCSBanking.ViewModels;

namespace TCSBanking.Controllers
{
    [Authorize(Roles = "AccountExecutive")]
    public class CustStatusBankController : Controller
    {
        private readonly ICustStatusBankRepo bankRepo;
        public CustStatusBankController(ICustStatusBankRepo users)
        {
            bankRepo = users;
        }

        public IActionResult AddCust()
        {
            var viewModel = new AddCustViewModel
            {
                UserInfos = bankRepo.UserInfor()
            };
            return View(viewModel);
        }


        [HttpPost]
        public IActionResult AddCust(AddCustViewModel VModel)
        {
            if (ModelState.IsValid)
            {
                var info = new UserInfo
                {
                    Ssnid = VModel.Ssnid,
                    Name = VModel.Name,
                    Address = VModel.Address1,
                    Age = VModel.Age
                };
                bankRepo.Addinfo(info);
                var status = new CustomerStatus
                {
                    CustomerId = info.CustomerId,
                    Ssnid = VModel.Ssnid,
                    Status = "Active",
                    Message = "Customer was recently created",
                    LastUpdated = DateTime.Now
                };
                CustomerStatus custStatus = bankRepo.Addstatus(status); 

                if(custStatus.CustomerId > 0)
                    return RedirectToAction("ViewCustomerStatus").WithSuccess("Success!", "The account " + custStatus.CustomerId + " was created.");
                else
                    return RedirectToAction("ViewCustomerStatus").WithDanger("Error ocurred", "The account was NOT created.");

            }
            return View(VModel);
        }

        //Used to display the Customer Status Table from the BankDB
        public IActionResult ViewCustomerStatus()
        {
            var users = bankRepo.CustomerStatuses();
            if (users.Count() == 0)
            {
                return RedirectToAction("Error");
            }
            else
            {
                return View(users);
            }
        }

        //If no records are in the Customer Status Table will print out no records
        public IActionResult ViewUserInfo()
        {
            var users = bankRepo.UserInfor();

            if (users.Count() == 0)
            {
                return RedirectToAction("Error");
            }
            else
            {
                return View(users);
            }
        }

        public IActionResult UpdateCust(int id)
        {
            var cust = bankRepo.GetCustById(id);

            var custEditViewModel = new EditCustViewModel
            {
                Ssnid = cust.Ssnid,
                Id = cust.CustomerId,
                Name = cust.Name,
                Address1 = cust.Address,
                Age = cust.Age

            };
            return View(custEditViewModel);
        }

        [HttpPost]
        public IActionResult UpdateCust(EditCustViewModel editCustViewModel)
        {
            if (ModelState.IsValid)
            {
                var customer = new UserInfo
                {
                    Ssnid = editCustViewModel.Ssnid,
                    CustomerId = editCustViewModel.Id,
                    Name = editCustViewModel.Name,
                    Address = editCustViewModel.Address1,
                    Age = editCustViewModel.Age
                };

                bankRepo.UpdateCust(customer);

                CustomerStatus status = bankRepo.GetStatusById(editCustViewModel.Id);
                var updatedStatus = new CustomerStatus
                {
                    Id = status.Id,
                    CustomerId = customer.CustomerId,
                    Ssnid = status.Ssnid,
                    Status = "Active",
                    Message = "Customer was recently edited",
                    LastUpdated = DateTime.Now
                };
                
                CustomerStatus custStatus = bankRepo.UpdateStatus(updatedStatus);
                if (custStatus.CustomerId > 0)
                    return RedirectToAction("ViewCustomerStatus").WithSuccess("Success!", "The account " + custStatus.CustomerId + " was updated.");
                else
                    return RedirectToAction("ViewCustomerStatus").WithDanger("Error ocurred", "The account was NOT updated.");
            }
            editCustViewModel.UserInfos = bankRepo.getUsers();
            return View(editCustViewModel);

        }

        public IActionResult DeleteCust(int id)
        {
            var cust = bankRepo.GetCustById(id);

            DeleteCustViewModel custInfo = new DeleteCustViewModel
            {
                Ssnid = cust.Ssnid,
                Id = cust.CustomerId,
                Name = cust.Name,
                Age = cust.Age,
                Address1 = cust.Address
            };
            return View(custInfo);
        }

        [HttpPost]
        public IActionResult DeleteCust(DeleteCustViewModel deleteCustViewModel)
        {

            if (ModelState.IsValid)
            {
                UserInfo deleted = bankRepo.GetCustById(deleteCustViewModel.Id);
                int ret = bankRepo.deleteCust(deleted);
                if (ret > 0)
                {
                    return RedirectToAction("ViewCustomerStatus").WithSuccess("Success!", "The customer " + deleteCustViewModel.Id + " was deleted.");
                }
                else
                {
                    return RedirectToAction("ViewCustomerStatus").WithDanger("Error occured!", "The customer was NOT deleted.");
                }

            }
            return View(deleteCustViewModel);
        }


        //If no records are in the Customer Status Table will print out no records
        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/CustStatusBank/AddCust.cshtml
@model TCSBanking.ViewModels.AddCustViewModel
@{
    ViewData["Title"] = "AddCust";
}

<html>
<head>
    <style>
    body { background-image: url("https://www.dozens.com/wp-content/uploads/2019/08/shop_loop.gif"); background-repeat: no-repeat; background-position: right bottom; }
    </style>
</head>
<body>

    

        <h1>Add Customer</h1>

        <form asp-controller="CustStatusBank" asp-action="addCust" method="post">
            <div class="form-group">
                <label asp-for="@Model.Ssnid"> 9-Digit Social Security Number </label>
                <input asp-for="@Model.Ssnid" class="form-control" placeholder="SSN">
                <span asp-validation-for="@Model.Ssnid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Name">Customer Name </label>
                <input asp-for="@Model.Name" class="form-control" placeholder="Name">
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Address1">Customer Address </label>
                <input asp-for="@Model.Address1" class="form-control" placeholder="Address">
                <span asp-validation-for="@Model.Address1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Age">Customer Age </label>
                <input asp-for="@Model.Age" class="form-control" placeholder="Age">
                <span asp-validation-for="@Model.Age" class="text-danger"></span>





            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
  
</body>
</html>

Views/CustStatusBank/DeleteCust.cshtml
@model TCSBanking.ViewModels.DeleteCustViewModel

@{ 
    ViewData["Title"] = "DeleteCust";
}

<h1>Delete Customer</h1>
<form asp-controller="CustStatusBank" asp-action="deleteCust" method="post">
    <div class="form-group">
        <label asp-for="@Model.Ssnid"> SSN Id </label>
        <input asp-for="@Model.Ssnid" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Id"> Customer Id </label>
        <input asp-for="@Model.Id" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Name"> Customer Name </label>
        <input asp-for="@Model.Name" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Age"> Customer Age </label>
        <input asp-for="@Model.Age" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Age" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Address1"> Customer Address </label>
        <input asp-for="@Model.Address1" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Address1" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/CustStatusBank/UpdateCust.cshtml
@model TCSBanking.ViewModels.EditCustViewModel
@{
    ViewData["Title"] = "UpdateCust";
}

<h1>Update Customer</h1>

<div class="align-content-md-center">
    <label asp-for="@Model.Ssnid"> Customer SSN ID </label>
    <label asp-for="@Model.Ssnid"> @Model.Ssnid </label>
</div>
<div class="align-content-md-center">
    <label asp-for="@Model.Id"> Customer ID </label>
    <label asp-for="@Model.Id"> @Model.Id </label>
</div>

<form asp-controller="CustStatusBank" asp-action="UpdateCust" method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <input type="hidden" asp-for="@Model.Ssnid" />
    <div class="align-content-md-center">
        <label asp-for="@Model.Name"> Old Customer Name: </label>
        <label asp-for="@Model.Name"> @Model.Name </label>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Name"> New Customer Name: </label>
        <input asp-for="@Model.Name" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
    </div>


    <div class="align-content-md-center">
        <label asp-for="@Model.Address1"> Old Address: </label>
        <label asp-for="@Model.Address1"> @Model.Address1 </label>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Address1"> New Address </label>
        <input asp-for="@Model.Address1" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Address1" class="text-danger"></span>
    </div>


    <div class="align-content-md-center">
        <label asp-for="@Model.Age"> Old Customer Age: </label>
        <label asp-for="@Model.Age"> @Model.Age </label>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Age"> New Customer Age </label>
        <input asp-for="@Model.Age" class="form-control" placeholder="Name" />
        <span asp-validation-for="@Model.Age" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/CustStatusBank/ViewCustomerStatus.cshtml
@model IEnumerable<CustomerStatus>
@{
    ViewData["Title"] = "List";
}

<h1>Customer Status</h1>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Customer ID</th>
            <th scope="col">SSN ID</th>
            <th scope="col">Status</th>
            <th scope="col">Message</th>
            <th scope="col">Last Updated</th>
            <th scope="col">Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var info in Model)
        {
            <tr>
                <td>@info.CustomerId</td>
                <td>@info.Ssnid</td>
                <td>@info.Status</td>
                <td>@info.Message</td>
                <td>@info.LastUpdated</td>
                <td class="text-center"><a class = "btn btn-primary" asp-controller="CustStatusBank" asp-action="ViewCustomerStatus">Refresh</a></td>
            </tr>
        }
    </tbody>
</table>

Views/CustStatusBank/ViewUserInfo.cshtml
@model IEnumerable<UserInfo>

@{ 
    ViewData["Title"] = "List";
} 

<h1>Customer Info</h1>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">SSN ID</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Age</th>
            <th scope="col">Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var info in Model)
        {
            <tr>
                <td>@info.Ssnid</td>
                <td>@info.Name</td>
                <td>@info.Address</td>
                <td>@info.Age</td>
                <td class="text-center btn-group">
                    <a class="btn btn-secondary" asp-controller="CustStatusBank" asp-action="UpdateCust" asp-route-id="@info.CustomerId">Update Customer</a>
                    <a class="btn btn-danger" asp-controller="CustStatusBank" asp-action="DeleteCust" asp-route-id="@info.CustomerId">Delete Customer</a>
                </td>
            </tr>
        }
    </tbody>
</table>