Models/AccountStatus.cs
using System;
using System.Collections.Generic;

namespace TCSBanking.Models
{
    public partial class AccountStatus
    {
        public int AccountId { get; set; }
        public string AccountType { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public DateTime LastUpdated { get; set; }
        public int Balance { get; set; }
        public int CustomerId { get; set; }

        public virtual UserInfo Customer { get; set; }
    }
}

Controllers/AccountStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TCSBanking.Extensions.Alerts;
using TCSBanking.Models;
using TCSBanking.Repositorys;
using TCSBanking.ViewModels;

namespace TCSBanking.Controllers
{
    [Authorize(Roles = "AccountExecutive")]
    public class AccountStatusController : Controller
    {
        private readonly IAccountStatusRepository _accountStatusRepository;

        public AccountStatusController(IAccountStatusRepository accountStatusRepository)
        {
            _accountStatusRepository = accountStatusRepository;
        }

        // GET - LIST OF ACCOUNTS
        public IActionResult List()
        {
            var accounts = _accountStatusRepository.getAccountStatuses();
            return View(accounts);
        }

        // GET - CREATE
        public IActionResult Create()
        {
            AccountCreateViewModel viewModel = new AccountCreateViewModel();
            return View(viewModel);
        }

        // POST - CREATE
        [HttpPost]
        public IActionResult Create(AccountCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                AccountStatus accountStatus = new AccountStatus
                {
                    CustomerId = viewModel.CustomerId,
                    AccountType = viewModel.AccountType,
                    Balance = viewModel.DepositAmount,
                    Status = "Active",
                    Message = "Account created.",
                    LastUpdated = DateTime.Now
                };

                var account = _accountStatusRepository.Add(accountStatus);
                if(account.AccountId > 0)
                    return RedirectToAction("List").WithSuccess("Success!", "The account " + account.AccountId +" was created.");
                else
                    return RedirectToAction("List").WithDanger("Error ocurred", "The account was NOT created.");
            }

            return View(viewModel);
        }

        // GET - SEARCH FORM
        public IActionResult Search()
        {
            AccountSearchViewModel viewModel = new AccountSearchViewModel();
            return View(viewModel);
        }

        // GET - SEARCH RESULTS
        [HttpGet]
        public IActionResult Search(AccountSearchViewModel viewModel)
        {
            viewModel.Accounts = _accountStatusRepository.getAccounts(viewModel.CustomerId);
            return View(viewModel);
        }

        // GET - DELETE 
        public IActionResult Delete(int Id)
        {

            AccountStatus account = _accountStatusRepository.GetAccountStatusById(Id);

            var accountDeleteViewModel = new AccountDeleteViewModel
            {
                CustomerId = account.CustomerId,
                AccountId = account.AccountId,
                AccountType = account.AccountType,
                Status = account.Status,
                Message = account.Message,
                LastUpdated = account.LastUpdated,
            };

            return View(accountDeleteViewModel);
        }

        // POST- DELETE
        [HttpPost]
        public IActionResult DeleteAccount(int Id)
        {
            int ret = _accountStatusRepository.deleteAccount(Id);
            if (ret > 0)
            {
                return RedirectToAction("List").WithSuccess("Success!", "The account " + Id + " was deleted.");
            }
            else
            {
                return RedirectToAction("List").WithDanger("Error occured!", "The account was not deleted.");
            }
        }
    }
}

Views/AccountStatus/Create.cshtml
@model TCSBanking.ViewModels.AccountCreateViewModel

<html>
<head>
    <style>
        body {
            background-image: url("https://www.fintecture.com/wp-content/themes/fintecture/img/Bank_8fps.gif");
            background-repeat: no-repeat;
            background-position: right bottom;
        }
    </style>
</head>
<body>

    <h1>Add Account</h1>

    <form asp-controller="AccountStatus" asp-action="Create" method="post">

        <div class="form-group">
            <label asp-for="@Model.CustomerId">Customer Id</label>
            <input asp-for="@Model.CustomerId" class="form-control" placeholder="Customer Id...">
            <span asp-validation-for="@Model.CustomerId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.AccountType">Account Type</label>
            <select asp-for="@Model.AccountType" class="browser-default custom-select">
                <option value="Savings" selected>Savings</option>
                <option value="Current">Current</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="@Model.DepositAmount">Deposit Amount</label>
            <input asp-for="@Model.DepositAmount" class="form-control" placeholder="Deposit Amount...">
            <span asp-validation-for="@Model.DepositAmount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-md btn-block">Create</button>
        </div>
    </form>
</body>
</html>

Views/AccountStatus/Delete.cshtml
@model TCSBanking.ViewModels.AccountDeleteViewModel


    <form asp-controller="AccountStatus" asp-action="DeleteAccount" asp-route-id="@Model.AccountId" method="post">
        <div class="form-group">
            <label asp-for="@Model.AccountId">Account Id</label>
            <input disabled asp-for="@Model.AccountId" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.CustomerId">Customer Id</label>
            <input disabled asp-for="@Model.CustomerId" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.AccountType">Account Type</label>
            <input disabled asp-for="@Model.AccountType" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.Status">Account Type</label>
            <input disabled asp-for="@Model.Status" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.Message">Account Type</label>
            <input disabled asp-for="@Model.Message" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.LastUpdated">Account Type</label>
            <input disabled asp-for="@Model.LastUpdated" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-md btn-block">Delete</button>
        </div>
    </form>


Views/AccountStatus/List.cshtml
@model IEnumerable<TCSBanking.Models.AccountStatus>

<h1>Account Status</h1>


<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Customer ID</th>
            <th>Account ID</th>
            <th>Account Type</th>
            <th>Account Status</th>
            <th>Message</th>
            <th>Last Updated</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.Any())
        {
<tr>
    <td colspan="3" class="text-center">
        <h4>No Accounts Found!</h4>
    </td>
</tr> }
            else
            {


@foreach (var account in Model)
{
<tr>
    <td>@account.CustomerId</td>
    <td>@account.AccountId</td>
    <td>@account.AccountType</td>
    <td>@account.Status</td>
    <td>@account.Message</td>
    <td>@account.LastUpdated</td>
    <td class="text-center">
        <a class="btn btn-primary" asp-action="List" asp-route-id="@account.AccountId">Refresh</a>
    </td>
</tr>}}
    </tbody>
</table>

@if (Model.Any())
{
    <div class="text-center">
        <a asp-action="List" class="btn btn-secondary">Refresh the list</a>
    </div>
}

Views/AccountStatus/Search.cshtml
@model TCSBanking.ViewModels.AccountSearchViewModel


<h1>Search Accounts</h1>

<form asp-controller="AccountStatus" asp-action="Search" method="get">
    <div class="form-group">
        <label asp-for="@Model.CustomerId">Customer Id / SSN Id</label>
        <input asp-for="@Model.CustomerId" class="form-control" placeholder="Customer Id or SSN Id...">
        <span asp-validation-for="@Model.CustomerId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-md btn-block">Get Accounts</button>
    </div>
</form>

@if (Model.Accounts.Any())
{

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Customer ID</th>
                <th>Account ID</th>
                <th>Account Type</th>
                <th>Account Status</th>
                <th>Message</th>
                <th>Last Updated</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var account in Model.Accounts)
            {
                <tr>
                    <td>@account.CustomerId</td>
                    <td>@account.AccountId</td>
                    <td>@account.AccountType</td>
                    <td>@account.Status</td>
                    <td>@account.Message</td>
                    <td>@account.LastUpdated</td>
                    <td class="text-center">
                        <a  class="btn btn-danger" asp-action="Delete" asp-controller="AccountStatus" asp-route-id="@account.AccountId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else @if (Model.CustomerId > 0)
{
<div class="text-center text-danger">
    <p>No Accounts under Customer ID / SSN ID @Model.CustomerId.</p>
</div>
}